steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/firastahir}/sampleapp"]
    env: ["PROJECT_ROOT=github.com/firastahir/sampleapp"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/composed-strata-222317/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/composed-strata-222317/gcp-cd-codelab:$REVISION_ID"
